# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: labelling-db
    image: postgres
    restart: always
    ports:
      - "5420:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USERNAME: postgres 
    volumes:
      - ./db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8069:8080
